// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stormy_SilverioAP1_P1.DAL;

#nullable disable

namespace Stormy_SilverioAP1_P1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260301050758_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stormy_SilverioAP1_P1.Models.DetallesHuacales", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("EntradaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradaId");

                    b.HasIndex("TipoId");

                    b.ToTable("DetallesHuacales");
                });

            modelBuilder.Entity("Stormy_SilverioAP1_P1.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntradaId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntradaId");

                    b.ToTable("EntradasHuacales");
                });

            modelBuilder.Entity("Stormy_SilverioAP1_P1.Models.TiposHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.HasKey("TipoId");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Rojo",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Verde",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 3,
                            Descripcion = "Azul",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("Stormy_SilverioAP1_P1.Models.DetallesHuacales", b =>
                {
                    b.HasOne("Stormy_SilverioAP1_P1.Models.EntradasHuacales", "EntradasHuacales")
                        .WithMany("ListaHuacales")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stormy_SilverioAP1_P1.Models.TiposHuacales", "TiposHuacales")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradasHuacales");

                    b.Navigation("TiposHuacales");
                });

            modelBuilder.Entity("Stormy_SilverioAP1_P1.Models.EntradasHuacales", b =>
                {
                    b.Navigation("ListaHuacales");
                });
#pragma warning restore 612, 618
        }
    }
}
